### PR TITLE
fix: Support new error schema from API

### LINKED ISSUE #113: Use new Error object from API

### PR DESCRIPTION
**Pull request by ghost**
Fixes #113, #107

### CODE REVIEW

File: src/error.ts [hunk 1]
```diff
@@ -5,14 +5,36 @@ import { AxiosError } from 'axios';
...
+    if (missing && missing.length > 0) {
+      message += '\nMissing:';
+      missing.forEach((item: object) => {
+        message += `\n  ${JSON.stringify(item)}`;
+      });
+    }
+    if (duplicated && duplicated.length > 0) {
+      message += '\nDuplicated:';
+      duplicated.forEach((item: object) => {
+        message += `\n  ${JSON.stringify(item)}`;
```
Comment (polomani) [inline src/error.ts]: I suggest to pass the entire `extra` object in `stringify()` instead of "stringifying" it manually

**Review by polomani — CHANGES_REQUESTED** [review]

**Review by polomani — APPROVED** [review]
LAwesomeTM
