### PR TITLE
v1.2.2 - Fix latest datapoint format

### LINKED ISSUE #16: `Datapoints.retrieveLatest` returns undefined
It seems from the test that expected response is
```
        data: {
          items: [
            {
              name: 'Cognite',
              datapoints,
            },
          ],
        },
```
but the real one from `https://api.cognitedata.com/api/0.5/projects/akerbp/timeseries/latest/IA_21PT1019.PV` is
```
"data": {
    "items": [
      {
        "timestamp": 1548140884056,
        "value": 0.054688
      }
    ]
  }
```

### PR DESCRIPTION
**Pull request by ghost**
Fixes #16

### CODE REVIEW

File: src/Datapoints.ts [hunk 1]
```diff
@@ -154,7 +154,7 @@ export class Datapoints {
     )}`;
     const params = { before };
     const response = (await rawGet(url, { params })) as AxiosResponse<any>;
-    return response.data.data.items[0].datapoints;
+    return response.data.data.items[0];
```
Comment (valgussev) [inline src/Datapoints.ts:165]: What if we have empty array in response?

Comment (ghost) [reply src/Datapoints.ts:165]: ~~Good catch 🚀 . Will push a fix~~

Comment (ghost) [reply src/Datapoints.ts:165]: No problem. In JS `[][0]` will return `undefined` and expected behaviour.
I have committed a new test for that.

**Review by valgussev — APPROVED** [review]
