### PR TITLE
v1.5.4 - Fix authorize problems

### LINKED ISSUE #62: 401 during calling `authorize`
If to pass `param` into `authorize` starting from some point of time an app receives back 401 error with the following requests stacking into an unresolved promise.
```
VM66:1 GET https://api.cognitedata.com/login/status 401 
```
```
https://api.cognitedata.com/login/token?token=ewogICJhbGciOiAiUlMyNTYiLAogICJ0eXAiOiAiSldUIgp9.ewogICJ1bmlxdWVfbmFtZSI6ICJ2YWxlcmlpLmd1c2V2QGNvZ25pdGUuY29tIiwKICAicHJvamVjdF9uYW1lIjogImFrZXJicCIsCiAgInNpZ25pbmdfa2V5IjogIjc0MDc4MWYzLTU2MTYtNGJmMC04NzY0LTAwMmZkNmZhNzFkMiIsCiAgImV4cGlyZV90aW1lIjogMTU1MTg3MTgyMgp9.RwYwilucNYp2jnrJoEkKWgFeq3ALg4KiJ4v16O8Tho5nMH9r%2B2B1QtXZlHr7ov3VCcrV7jf4g7%2Ba6GBNDS6svaWz8vqOltulGUp59i8pWMaplP6%2BvSzcr2V8U3PEtMwajNLxa6teD0kDoeLhIkY4h9%2Fe3tGNVerb0a9MnXuQjL7xTcALuqRTxlk8BWsd%2FlJxsbBW2LeevYftmDwA4ZGgh28rKM%2F%2BovuPq3Tq7nPS6%2Fr6AaY%2FoEuc3at%2FEcm1CYMgTVq97B5hfJKfU36MVZwCKAF75ASKui%2F1%2FgksMZWrS7PfWVeS6tBstT9z9XP1%2FGuGcSF%2FCBUCkASo9%2BQj7EXtuQ%3D%3D  401
```

### PR DESCRIPTION
**Pull request by ghost**
- Don't export an es-module file since `jwtDecode` doesn't work with it
- Clear `Authorization` before using endpoint `/login/token` to avoid `401`s
- Call `cancelSchedule` in `scheduleRenewal` to avoid infinite login loop
- Throw exception on invalid `idToken`

Should (hopefully) fix:
Fixes #62, #61

### CODE REVIEW

**Review by ghost — APPROVED** [review]
LGTM :+1:

File: src/Login.ts [hunk 1]
```diff
@@ -235,9 +235,12 @@ export class Login {
   public static async validateJWT(token: string): Promise<TokenStatus> {
     const url = `${loginUrl()}/token`;
     const params = { token };
+    const authHeader = instance.defaults.headers.Authorization;
```
Comment (valgussev) [inline src/Login.ts:238]: We can use `setBearerToken('')` here instead

Comment (ghost) [reply src/Login.ts:238]: That doesn't remove the header. We also need to restore the previous `Authorization`-header after the request

Comment (valgussev) [reply src/Login.ts:238]: Just set `setBearerToken(accessToken);` only after `Login.validateJWT(idToken)`

Comment (ghost) [reply src/Login.ts:238]: It will not work since if you loggin the second time the Authorization header is already set. The request will fail if `Authorization: Bearer `. It needs to be completely removed.

**Review by valgussev — APPROVED** [review]

File: src/Login.ts (hunk 1 above)
Comment (valgussev) [reply src/Login.ts:238]: Alright, hope you know what you are doing :)
